# -*- coding: utf-8 -*-
"""milk-formula-market-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNbD37KtKdL67dJuM8ET2un2obWn9hxi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (12, 5)
plt.rcParams['font.size'] = 11

print("Semua library berhasil di-import!")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Formulated Milk Product - fmcg_milk_powder_dataset_50000.csv')

print(f"Data berhasil dimuat!")
print(f"   Jumlah baris  : {df.shape[0]:,}")   # .shape[0] = jumlah baris
print(f"   Jumlah kolom  : {df.shape[1]}")      # .shape[1] = jumlah kolom
print(f"\nNama kolom yang tersedia:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2}. {col}")

print("\n" + "="*60)
print("BLOK 3: MENGENAL ISI DATA")
print("="*60)

# Lihat 5 baris pertama
print("\n--- 5 BARIS PERTAMA DATA ---")
print(df.head())

# Info umum: tipe data tiap kolom & ada tidaknya data kosong
print("\n--- INFO KOLOM & TIPE DATA ---")
print(df.info())

# Statistik dasar untuk kolom angka
# count=jumlah data, mean=rata-rata, std=standar deviasi
# min=terkecil, max=terbesar
print("\n--- STATISTIK DASAR (kolom angka) ---")
print(df.describe().round(2))

print("\n" + "="*60)
print("BLOK 4: CEK KUALITAS DATA")
print("="*60)

# --- 4A. Cek nilai kosong (missing values) ---
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({
    'Jumlah Kosong': missing,
    'Persen (%)': missing_pct
}).query('`Jumlah Kosong` > 0')

if len(missing_df) == 0:
    print("\n✅ Tidak ada nilai kosong (missing values) — data bersih!")
else:
    print("\n⚠️  Kolom dengan nilai kosong:")
    print(missing_df)

# --- 4B. Cek data duplikat ---
duplikat = df.duplicated().sum()
print(f"\n{'✅' if duplikat == 0 else '⚠️ '} Data duplikat: {duplikat} baris")

# --- 4C. Cek nilai unik di kolom kategorikal ---
# Kolom kategorikal = kolom berisi teks/label, bukan angka
kolom_kategorikal = ['gender', 'age_group', 'income_bracket', 'loyalty_member',
                     'product_category', 'product_subcategory', 'brand',
                     'promo_applied', 'will_purchase_milk', 'day_of_week']

print("\n--- NILAI UNIK PER KOLOM KATEGORIKAL ---")
for col in kolom_kategorikal:
    nilai_unik = df[col].unique()
    print(f"  {col:<30} → {list(nilai_unik)}")

# --- 4D. Perbaiki tipe data kolom tanggal ---
df['transaction_date'] = pd.to_datetime(df['transaction_date'])
print(f"\n✅ Kolom 'transaction_date' sudah diubah ke format tanggal")

# --- 4E. Buat kolom baru: revenue per transaksi ---
df['revenue'] = df['unit_price'] * df['quantity']
print(f"✅ Kolom baru 'revenue' berhasil dibuat (unit_price × quantity)")

print("\n" + "="*60)
print("BLOK 5: ANALISIS UNIVARIAT")
print("="*60)

# --- 5A. Distribusi Brand ---
print("\n--- DISTRIBUSI BRAND ---")
brand_count = df['brand'].value_counts()
brand_pct   = df['brand'].value_counts(normalize=True).mul(100).round(1)
tabel_brand = pd.DataFrame({
    'Jumlah Transaksi': brand_count,
    'Persentase (%)': brand_pct
})
print(tabel_brand)

# --- 5B. Distribusi Kategori Produk ---
print("\n--- DISTRIBUSI KATEGORI PRODUK ---")
cat_count = df['product_category'].value_counts()
cat_pct   = df['product_category'].value_counts(normalize=True).mul(100).round(1)
tabel_cat = pd.DataFrame({
    'Jumlah Transaksi': cat_count,
    'Persentase (%)': cat_pct
})
print(tabel_cat)

# --- 5C. Distribusi Gender ---
print("\n--- DISTRIBUSI GENDER ---")
print(df['gender'].value_counts())

# --- 5D. Distribusi Income Bracket ---
print("\n--- DISTRIBUSI INCOME BRACKET ---")
print(df['income_bracket'].value_counts())

# --- 5E. Statistik kolom numerik penting ---
print("\n--- STATISTIK REVENUE PER TRANSAKSI ---")
print(df['revenue'].describe().round(2))

print("\n" + "="*60)
print("BLOK 6: ANALISIS BIVARIAT")
print("="*60)

# --- 6A. PERTANYAAN UTAMA: Apakah promo efektif? ---
print("\n--- EFEKTIVITAS PROMO TERHADAP KONVERSI PEMBELIAN ---")
konversi_promo = df.groupby('promo_applied')['will_purchase_milk'].apply(
    lambda x: round((x == 'Yes').mean() * 100, 1)
).rename('Conversion Rate (%)')
print(konversi_promo)

# Hitung peningkatan (lift)
rate_dengan_promo = konversi_promo.get('Yes', 0)
rate_tanpa_promo  = konversi_promo.get('No', 0)
lift = round(((rate_dengan_promo - rate_tanpa_promo) / rate_tanpa_promo) * 100, 1)
print(f"\n💡 INSIGHT: Promo meningkatkan konversi sebesar +{lift}%")
print(f"   Tanpa promo : {rate_tanpa_promo}%")
print(f"   Dengan promo: {rate_dengan_promo}%")

# --- 6B. Revenue per Brand ---
print("\n--- REVENUE PER BRAND ---")
revenue_brand = df.groupby('brand')['revenue'].sum().sort_values(ascending=False)
print(revenue_brand.apply(lambda x: f"{x:,.0f}"))

# --- 6C. Rata-rata pengeluaran per kelompok usia ---
print("\n--- RATA-RATA PENGELUARAN BULANAN PER USIA ---")
spend_usia = df.groupby('age_group')['avg_monthly_spend'].mean().round(1).sort_index()
print(spend_usia)
print("\n💡 INSIGHT: Semua kelompok usia memiliki pengeluaran hampir sama")
print("   → Strategi pemasaran berbasis usia kurang efektif")

# --- 6D. Konversi berdasarkan Income ---
print("\n--- KONVERSI BERDASARKAN INCOME BRACKET ---")
konversi_income = df.groupby('income_bracket')['will_purchase_milk'].apply(
    lambda x: round((x == 'Yes').mean() * 100, 1)
).rename('Conversion Rate (%)')
print(konversi_income)
print("\n💡 INSIGHT: Income tidak berpengaruh signifikan pada keputusan beli")
print("   → Susu formula adalah kebutuhan esensial, tidak tergantung daya beli")

# --- 6E. Revenue per bulan (tren) ---
print("\n--- REVENUE PER BULAN ---")
nama_bulan = {1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'Mei', 6:'Jun',
              7:'Jul', 8:'Agu', 9:'Sep', 10:'Okt', 11:'Nov', 12:'Des'}
revenue_bulan = df.groupby('month')['revenue'].sum()
revenue_bulan.index = revenue_bulan.index.map(nama_bulan)
for bulan, rev in revenue_bulan.items():
    bar = '█' * int(rev / 15000)   # visualisasi sederhana di terminal
    print(f"  {bulan:3} | {bar} {rev:>10,.0f}")

bulan_peak = revenue_bulan.idxmax()
bulan_terendah = revenue_bulan.idxmin()
print(f"\n💡 Revenue tertinggi : {bulan_peak} ({revenue_bulan.max():,.0f})")
print(f"   Revenue terendah  : {bulan_terendah} ({revenue_bulan.min():,.0f})")

# --- 6F. Analisis hari dalam seminggu ---
print("\n--- RATA-RATA BASKET VALUE PER HARI ---")
urut_hari = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
basket_hari = df.groupby('day_of_week')['total_basket_value'].mean().round(1)
basket_hari = basket_hari.reindex(urut_hari)
print(basket_hari)

print("\n" + "="*60)
print("BLOK 7: ANALISIS MULTIVARIAT - KORELASI")
print("="*60)

# Pilih hanya kolom numerik
kolom_numerik = ['unit_price', 'quantity', 'total_basket_value',
                 'discount_rate', 'last_purchase_days',
                 'category_frequency_milk', 'avg_monthly_spend',
                 'loyalty_points_used', 'revenue']

korelasi = df[kolom_numerik].corr().round(2)

# Tampilkan korelasi dengan kolom revenue (paling relevan)
print("\n--- KORELASI DENGAN REVENUE ---")
korelasi_revenue = korelasi['revenue'].sort_values(ascending=False)
print(korelasi_revenue)
print("\nCatatan: nilai mendekati 1 = korelasi positif kuat")
print("         nilai mendekati -1 = korelasi negatif kuat")
print("         nilai mendekati 0 = tidak ada korelasi")

print("\n" + "="*60)
print("BLOK 8: SEGMENTASI PELANGGAN")
print("="*60)

# Fungsi segmentasi berdasarkan rata-rata pengeluaran bulanan
def segmentasi_pelanggan(spend):
    if spend >= 400:
        return 'High Value'
    elif spend >= 250:
        return 'Medium Value'
    else:
        return 'Low Value'

# Buat kolom segmen baru
df['segmen'] = df['avg_monthly_spend'].apply(segmentasi_pelanggan)

print("\n--- DISTRIBUSI SEGMEN PELANGGAN ---")
segmen_count = df['segmen'].value_counts()
segmen_pct   = df['segmen'].value_counts(normalize=True).mul(100).round(1)
tabel_segmen = pd.DataFrame({
    'Jumlah': segmen_count,
    'Persen (%)': segmen_pct
})
print(tabel_segmen)

# Analisis konversi per segmen
print("\n--- KONVERSI PER SEGMEN ---")
konversi_segmen = df.groupby('segmen')['will_purchase_milk'].apply(
    lambda x: round((x == 'Yes').mean() * 100, 1)
).rename('Conversion Rate (%)')
print(konversi_segmen)

print("\n" + "="*60)
print("BLOK 9: MEMBUAT VISUALISASI")
print("="*60)

fig, axes = plt.subplots(3, 2, figsize=(16, 18))
fig.suptitle('Dashboard Analisis FMCG - Produk Susu Formula',
             fontsize=16, fontweight='bold', y=0.98)

# --- Chart 1: Revenue per Brand ---
ax1 = axes[0, 0]
revenue_brand_sorted = revenue_brand.sort_values(ascending=True)
bars = ax1.barh(revenue_brand_sorted.index, revenue_brand_sorted.values,
                color=['#2196F3', '#4CAF50', '#FF9800', '#9C27B0'])
ax1.set_title('Revenue per Brand', fontweight='bold')
ax1.set_xlabel('Total Revenue')
# Tambahkan label angka di ujung bar
for bar, val in zip(bars, revenue_brand_sorted.values):
    ax1.text(val + 5000, bar.get_y() + bar.get_height()/2,
             f'{val:,.0f}', va='center', fontsize=9)
ax1.set_xlim(0, revenue_brand_sorted.max() * 1.15)

# --- Chart 2: Distribusi Kategori (Pie Chart) ---
ax2 = axes[0, 1]
cat_data = df['product_category'].value_counts()
colors_pie = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4']
wedges, texts, autotexts = ax2.pie(
    cat_data.values,
    labels=cat_data.index,
    autopct='%1.1f%%',
    colors=colors_pie,
    startangle=90
)
ax2.set_title('Distribusi Kategori Produk', fontweight='bold')

# --- Chart 3: Efektivitas Promo (Bar Chart) ---
ax3 = axes[1, 0]
promo_labels = ['Tanpa Promo', 'Dengan Promo']
promo_values = [rate_tanpa_promo, rate_dengan_promo]
bars3 = ax3.bar(promo_labels, promo_values,
                color=['#FF7043', '#43A047'], width=0.5, edgecolor='white')
ax3.set_title('Efektivitas Promo → Conversion Rate', fontweight='bold')
ax3.set_ylabel('Conversion Rate (%)')
ax3.set_ylim(0, 55)
# Tambahkan label angka di atas bar
for bar, val in zip(bars3, promo_values):
    ax3.text(bar.get_x() + bar.get_width()/2, val + 1,
             f'{val}%', ha='center', fontweight='bold', fontsize=12)
# Tambahkan garis lift
ax3.annotate('', xy=(1, rate_dengan_promo), xytext=(0, rate_tanpa_promo),
             arrowprops=dict(arrowstyle='<->', color='gray', lw=1.5))
ax3.text(0.5, (rate_dengan_promo + rate_tanpa_promo)/2,
         f'+{lift}%', ha='center', color='gray', fontsize=10)

# --- Chart 4: Tren Revenue Bulanan (Line Chart) ---
ax4 = axes[1, 1]
revenue_bulan_vals = df.groupby('month')['revenue'].sum()
ax4.plot(range(1, 13), revenue_bulan_vals.values,
         marker='o', linewidth=2.5, color='#1565C0',
         markersize=8, markerfacecolor='white', markeredgewidth=2)
ax4.fill_between(range(1, 13), revenue_bulan_vals.values,
                 alpha=0.1, color='#1565C0')
ax4.set_title('Tren Revenue Bulanan', fontweight='bold')
ax4.set_xlabel('Bulan')
ax4.set_ylabel('Total Revenue')
ax4.set_xticks(range(1, 13))
ax4.set_xticklabels(['Jan','Feb','Mar','Apr','Mei','Jun',
                     'Jul','Agu','Sep','Okt','Nov','Des'], fontsize=9)
ax4.set_ylim(revenue_bulan_vals.min() * 0.95, revenue_bulan_vals.max() * 1.05)
# Tandai bulan tertinggi
max_idx = revenue_bulan_vals.argmax() + 1
ax4.annotate(f'Peak\n{revenue_bulan_vals.max():,.0f}',
             xy=(max_idx, revenue_bulan_vals.max()),
             xytext=(max_idx + 1.5, revenue_bulan_vals.max()),
             fontsize=8, color='#1565C0',
             arrowprops=dict(arrowstyle='->', color='#1565C0', lw=1))

# --- Chart 5: Avg Spend per Usia (Bar Chart) ---
ax5 = axes[2, 0]
spend_usia_sorted = df.groupby('age_group')['avg_monthly_spend'].mean().sort_index()
bars5 = ax5.bar(spend_usia_sorted.index, spend_usia_sorted.values,
                color='#7B1FA2', alpha=0.8, edgecolor='white')
ax5.set_title('Rata-rata Pengeluaran per Kelompok Usia', fontweight='bold')
ax5.set_ylabel('Avg Monthly Spend')
ax5.set_ylim(300, 340)  # zoom in supaya perbedaan kecil terlihat
for bar, val in zip(bars5, spend_usia_sorted.values):
    ax5.text(bar.get_x() + bar.get_width()/2, val + 0.5,
             f'{val:.1f}', ha='center', fontsize=9)
# Tambahkan catatan
ax5.text(0.5, 0.05, 'Catatan: perbedaan sangat kecil → usia bukan faktor utama',
         transform=ax5.transAxes, ha='center', fontsize=8,
         style='italic', color='gray')

# --- Chart 6: Heatmap Korelasi ---
ax6 = axes[2, 1]
# Pilih 6 kolom saja supaya heatmap tidak terlalu penuh
kolom_heatmap = ['unit_price', 'quantity', 'discount_rate',
                 'avg_monthly_spend', 'loyalty_points_used', 'revenue']
sns.heatmap(df[kolom_heatmap].corr(),
            annot=True, fmt='.2f', cmap='RdYlGn',
            ax=ax6, square=True, linewidths=0.5,
            cbar_kws={'shrink': 0.8})
ax6.set_title('Heatmap Korelasi Variabel Numerik', fontweight='bold')
ax6.tick_params(axis='x', rotation=45)
ax6.tick_params(axis='y', rotation=0)

plt.tight_layout()
plt.savefig('dashboard_analisis.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Dashboard chart berhasil dibuat & disimpan sebagai 'dashboard_analisis.png'")

print("\n" + "="*60)
print("BLOK 10: RINGKASAN INSIGHT & REKOMENDASI BISNIS")
print("="*60)

total_revenue = df['revenue'].sum()
avg_basket    = df['total_basket_value'].mean()
overall_conv  = (df['will_purchase_milk'] == 'Yes').mean() * 100
top_brand     = revenue_brand.idxmax()
peak_month    = revenue_bulan.idxmax()

print(f"""
┌─────────────────────────────────────────────────────────┐
│  RINGKASAN EKSEKUTIF                                    │
├─────────────────────────────────────────────────────────┤
│  Total Transaksi     : {len(df):>10,} transaksi           │
│  Total Revenue       : {total_revenue:>10,.0f} unit-Rp         │
│  Avg Basket Value    : {avg_basket:>10.1f} per transaksi    │
│  Overall Conv. Rate  : {overall_conv:>9.1f}%                   │
│  Brand Teratas       : {top_brand:<15}               │
│  Bulan Puncak        : {peak_month:<15}               │
└─────────────────────────────────────────────────────────┘
""")

insights = [
    ("INSIGHT 1", "Promo sangat efektif",
     f"Meningkatkan konversi dari {rate_tanpa_promo}% → {rate_dengan_promo}% (+{lift}%)",
     "Perluas cakupan promo, saat ini baru 39.8% transaksi yang pakai promo"),

    ("INSIGHT 2", "Persaingan brand sangat ketat",
     "Selisih revenue antar 4 brand hanya ~40K (2-3%) — tidak ada dominasi jelas",
     "Diferensiasi produk & brand loyalty program bisa jadi keunggulan kompetitif"),

    ("INSIGHT 3", "Usia & income tidak pengaruhi keputusan beli",
     "Conversion rate hampir identik di semua segmen demografis",
     "Gunakan behavioral segmentation (frekuensi beli, recency) bukan demografis"),

    ("INSIGHT 4", "Revenue sangat stabil sepanjang tahun",
     f"Variasi bulanan hanya ±{(revenue_bulan.max()-revenue_bulan.min())/revenue_bulan.mean()*100:.1f}% — demand inelastik",
     "Manfaatkan untuk just-in-time inventory planning & efisiensi gudang"),

    ("INSIGHT 5", "Stage 4 & Lactose-Free paling diminati",
     "Stage 4: 10,169 transaksi | Lactose-Free: 10,024 transaksi",
     "Prioritaskan stok & promosi untuk dua subkategori ini"),
]

for kode, judul, temuan, rekomendasi in insights:
    print(f"  [{kode}] {judul}")
    print(f"   Temuan     : {temuan}")
    print(f"   Aksi       : {rekomendasi}")
    print()

print("="*60)
print("✅ Analisis selesai! Semua output tersimpan.")
print("   File chart: dashboard_analisis.png")
print("="*60)

print("\n" + "="*60)
print("BLOK 11 (BONUS): PREDIKSI PEMBELIAN - MACHINE LEARNING")
print("="*60)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# --- Siapkan fitur (X) dan target (y) ---
fitur_kolom = ['age_group', 'gender', 'income_bracket', 'loyalty_member',
               'promo_applied', 'unit_price', 'quantity',
               'avg_monthly_spend', 'category_frequency_milk',
               'last_purchase_days', 'loyalty_points_used']

df_model = df[fitur_kolom + ['will_purchase_milk']].copy()

# Ubah kolom teks menjadi angka (ML butuh angka, bukan teks)
le = LabelEncoder()
kolom_teks = ['age_group', 'gender', 'income_bracket',
              'loyalty_member', 'promo_applied']
for col in kolom_teks:
    df_model[col] = le.fit_transform(df_model[col])

X = df_model[fitur_kolom]
y = (df_model['will_purchase_milk'] == 'Yes').astype(int)
# y = 1 berarti "akan beli", y = 0 berarti "tidak beli"

# --- Bagi data: 80% untuk melatih model, 20% untuk uji ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42  # random_state=42 supaya hasil konsisten
)
print(f"\nData training : {len(X_train):,} baris")
print(f"Data testing  : {len(X_test):,} baris")

# --- Latih model Random Forest ---
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# --- Evaluasi model ---
y_pred = model.predict(X_test)
akurasi = accuracy_score(y_test, y_pred) * 100

print(f"\n--- HASIL EVALUASI MODEL ---")
print(f"Akurasi model : {akurasi:.1f}%")
print(f"\nLaporan detail:")
print(classification_report(y_test, y_pred,
      target_names=['Tidak Beli', 'Akan Beli']))

# --- Fitur terpenting ---
print("\n--- FITUR YANG PALING BERPENGARUH ---")
importance_df = pd.DataFrame({
    'Fitur': fitur_kolom,
    'Kepentingan': model.feature_importances_
}).sort_values('Kepentingan', ascending=False)

for _, row in importance_df.iterrows():
    bar = '█' * int(row['Kepentingan'] * 200)
    print(f"  {row['Fitur']:<30} {bar} {row['Kepentingan']:.3f}")

top_fitur = importance_df.iloc[0]['Fitur']
print(f"\n💡 Fitur paling menentukan: '{top_fitur}'")
print(f"   → Ini adalah variabel yang paling mempengaruhi")
print(f"     apakah pelanggan akan membeli susu formula atau tidak")

print("\n" + "="*60)
print("  SELAMAT! Kamu sudah menyelesaikan analisis data lengkap")
print("  dari load data → cleaning → EDA → visualisasi → ML")
print("="*60)